filter:
    excluded_paths:
        - 'src/WidgetGenerator.php'
        - 'tests/*'

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
                coverage:
                    file: 'some-file'
                    format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
