name: tests

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3]
        laravel: [6.*, 7.*, 8.*, 9.*, 10.*]
        exclude:
          - php: 7.2
            laravel: 8.*
          - php: 7.2
            laravel: 9.*
          - php: 7.3
            laravel: 9.*
          - php: 7.4
            laravel: 9.*
          - php: 7.2
            laravel: 10.*
          - php: 7.3
            laravel: 10.*
          - php: 7.4
            laravel: 10.*
          - php: 8.0
            laravel: 10.*
          - php: 8.0
            laravel: 7.*
          - php: 8.1
            laravel: 7.*
          - php: 8.2
            laravel: 7.*
          - php: 8.3
            laravel: 7.*
          - php: 8.0
            laravel: 6.*
          - php: 8.1
            laravel: 6.*
          - php: 8.2
            laravel: 6.*
          - php: 8.3
            laravel: 6.*
          - php: 7.2
            laravel: 11.*
          - php: 7.3
            laravel: 11.*
          - php: 7.4
            laravel: 11.*
          - php: 8.0
            laravel: 11.*
          - php: 8.1
            laravel: 11.*
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - OS ${{ matrix.os }}

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            fetch-depth: 3
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ matrix.php }}
              extensions: mbstring, exif, iconv, tokenizer, fileinfo, xdebug
              coverage: xdebug

        - name: Install dependencies
          run: |
              composer require "laravel/framework=${{ matrix.laravel }}" --no-update
              composer update --prefer-dist --no-interaction --no-progress

        - name: PHPUnit
          run: |
            ./vendor/bin/phpunit --stop-on-failure --coverage-clover ./coverage.xml
          env:
            XDEBUG_MODE: coverage
      
        - name: Upload Scrutinizer coverage
          uses: sudo-bot/action-scrutinizer@latest
          if: github.repository == 'imanghafoori1/laravel-widgetize'
          with:
            cli-args: "--format=php-clover ./coverage.xml --revision=${{ github.event.pull_request.head.sha || github.sha }}"
